### PR TITLE
Added linkCallbackFactory

### LINKED ISSUE #150: Add callback for following hyperlink
Currently hyperlinks are hard-coded to launch the browser, this needs to be configurable.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #150

### CODE REVIEW

**Comment by dlemmermann** [comment]
Why do we have to first invoke a function on the node that returns the actual consumer of the hyperlink? I can't really think of any use case where links are followed differently based on the underlying scene graph node.

**Comment by dlemmermann** [comment]
After careful reconsideration @sten-navie and I realised that the app might wanna display an intermediate UI when the user clicks on a hyperlink. Having the clicked node becomes very useful then.

**Comment by jperedadnr** [comment]
Note also that the callback can be applied also to `ImageView`, so I take you need at least different functionality for Text/Image links

**Review by abhinayagarwal — APPROVED** [review]
PR looks good. My preference would be to perform the callback action on CTRL+MOUSE_CLICKED instead to improve UX.

**Comment by jperedadnr** [comment]
Yes, this could be done in a follow-up issue.

**Pull request merged**
