### PR TITLE
Add support for drag and drop

### LINKED ISSUE #112: Support drag and drop of images
The user should be able to drop an image into any location of the text.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #112 

@dlemmermann I've started reviewing your PR #142 , but since it required many changes, I ended up doing a new PR, with some extra features (like image checks, hyperlink and caret movement), if you don't mind.

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
While drag-dropping a hyperlink in between 2 words, the previous word seems to be always selected before the hyperlink is pasted resulting in the first word becoming a hyperlink. This might not always be the desired result.

**Comment by jperedadnr** [comment]
What do you propose in that case?

**Comment by abhinayagarwal** [comment]
The link should be pasted as it is between the two words?

**Comment by dlemmermann** [comment]
@jperedadnr I don't mind :-)

**Review by abhinayagarwal — APPROVED** [review]

**Review by johanvos — APPROVED** [review]

**Review by abhinayagarwal — APPROVED** [review]

**Pull request merged**
