### PR TITLE
Introduce FaceModel and change ViewModel when needed

### LINKED ISSUE #60: Control should be able to set (and get) the text and decorations.
So far, the skin uses a single viewModel with a hardcoded text as original text for the model, without decorations.

The control should have a property that sets the original text and decoration, which the skin should listen to in order to create a new viewModel with that text and decorations.

Also the control should have another readOnly property with the actual value of the text and decorations.

These properties would serialization/deserialization in a later step.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #60 
This is just a tentative approach...

FaceModel could have a better name. The property in the control so far can only be set with a given "initial" model. It doesn't read the "final" model after changes yet.

### CODE REVIEW

**Comment by eugener** [comment]
To be honest, I'm not sure I understand what it represents. 
I agree that document (or "control model") needs text fragments with attributes, but I'm not sure it needs caret position. Do we need to store it?

I would also think that it has to be based on an interface, so users can implement different format loaders (rtf, ms word or something else). Since it represents the "final", stored state, we can  just store text fragments in sequence, which means that our interface is just an iterator over those fragments. By fragment I mean `text + its decorations`, of course.  Internally this can easily be converted to `piece table`.

**Comment by jperedadnr** [comment]
The caret position is a way to persist the user's last location. But when you open the document again, it is a way to go to the last place where the user was working. It is optional of course and it can be out for now.

We can add an interface, sure. Also, we can find a better name to it.

**Comment by jperedadnr** [comment]
@eugener Based on your [comment](https://github.com/gluonhq/rich-text-area/pull/53#discussion_r813475851), I'm using now one single ViewModel. When FaceModel changes, we simply create a new TextBuffer.

**Comment by jperedadnr** [comment]
The changes are ready, at least for a first iteration.

**Comment by jperedadnr** [comment]
@eugener I've finally got a working solution for the actions, but it depends on this PR. Before I can raise a new PR, it would be good to get this one merged. 
Or should I add my changes on top of the current PR (but it will be more complex to review).

**Comment by eugener** [comment]
Feel free to merge! :)

**Pull request merged**
